apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- if eq .Values.service.type "Headless" }}
  clusterIP: None
  {{- end }}
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port | default 8080 }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      name: {{ .Values.service.portName | default "http" }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
